import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';

test('complete real WebAuthn, resident, gate, admin and offline PWA journeys', async ({ page, context, browser }) => {
  const fixture = JSON.parse(await readFile('test-results/bootstrap.json', 'utf8'));
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  const cdp = await context.newCDPSession(page); await cdp.send('WebAuthn.enable');
  await cdp.send('WebAuthn.addVirtualAuthenticator', { options: { protocol: 'ctap2', transport: 'internal', hasResidentKey: true, hasUserVerification: true, isUserVerified: true, automaticPresenceSimulation: true } });
  await page.goto('/'); await expect(page.getByRole('heading', { name: 'Qué gusto verte.' })).toBeVisible();
  await page.screenshot({ path: 'test-results/login-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Activar mi acceso', exact: true }).click();
  await page.getByLabel('Invitación de acceso').fill(fixture.enrollmentToken);
  await page.getByRole('button', { name: 'Activar mi acceso', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Hola, Lucía.' })).toBeVisible();
  await expect(page.getByRole('button', { name: /Diego Ramírez/ })).toBeVisible();
  await page.screenshot({ path: 'test-results/dashboard-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Crear pase', exact: true }).click();
  await page.getByLabel('Nombre del visitante').fill('Valeria Pérez');
  await page.getByLabel('Placas del vehículo').fill('VAL-123');
  await page.getByRole('button', { name: 'Revisar pase' }).click();
  await page.getByRole('button', { name: 'Crear pase', exact: true }).last().click();
  await expect(page.getByRole('dialog', { name: 'Tu pase está listo' })).toBeVisible();
  const shared = await page.getByRole('textbox', { name: 'Enlace del pase', exact: true }).inputValue();
  await expect(page.getByRole('img', { name: 'Código QR de acceso' })).toBeVisible();
  await page.getByRole('button', { name: 'Cerrar', exact: true }).click();
  await page.getByRole('navigation', { name: 'Navegación principal' }).getByRole('button', { name: 'Mis pases', exact: true }).click();
  await page.getByRole('button', { name: /Valeria Pérez/ }).click(); await expect(page.getByRole('button', { name: 'Ver QR' })).toBeVisible();
  await page.getByRole('button', { name: 'Cancelar pase', exact: true }).click();
  await page.getByRole('dialog', { name: '¿Cancelar este pase?' }).getByRole('button', { name: 'Cancelar pase' }).click();
  await expect(page.getByRole('button', { name: /Valeria Pérez/ })).toContainText('Cancelado');
  await page.getByLabel('Seleccionar vivienda').selectOption(fixture.otherPropertyId);
  await expect(page.getByRole('heading', { name: 'Tu próxima visita empieza aquí' })).toBeVisible();
  await expect(page.getByRole('button', { name: /Valeria Pérez/ })).toHaveCount(0);
  await page.getByLabel('Seleccionar vivienda').selectOption(fixture.propertyId);
  await page.getByRole('navigation', { name: 'Navegación principal' }).getByRole('button', { name: 'Caseta', exact: true }).click();
  await page.getByRole('combobox', { name: 'Caseta', exact: true }).selectOption(fixture.gateId);
  await page.getByLabel('Clave del dispositivo').fill(fixture.deviceToken);
  await page.getByRole('button', { name: 'Conectar caseta' }).click();
  await page.getByRole('button', { name: 'Abrir cámara', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Acceso autorizado' })).toBeVisible();
  await page.getByRole('button', { name: 'Siguiente visita' }).click();
  await page.getByLabel('Enlace o token del pase').fill(fixture.scanUrl);
  await page.getByRole('button', { name: 'Validar', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'No autorices el acceso' })).toBeVisible();
  await expect(page.getByText('Este pase ya fue utilizado.')).toBeVisible();
  await page.getByRole('navigation', { name: 'Navegación principal' }).getByRole('button', { name: 'Administración' }).click();
  await page.getByRole('button', { name: /Ana Torres ana@e2e.test/ }).click();
  await page.getByRole('combobox', { name: 'Vivienda', exact: true }).selectOption(fixture.propertyId);
  await page.getByLabel('Verifiqué la identidad').check();
  await page.getByRole('button', { name: 'Crear invitación', exact: true }).click();
  await expect(page.getByText('Invitación creada', { exact: true })).toBeVisible();
  const residentInvite = await page.getByLabel('Enlace de activación').inputValue();
  await page.getByRole('button', { name: 'Dispositivos de caseta', exact: true }).click();
  await page.getByRole('button', { name: 'Agregar equipo' }).click();
  await page.getByLabel('Nombre del equipo').fill('Tableta de visitas');
  await page.getByRole('combobox', { name: 'Caseta', exact: true }).selectOption(fixture.gateId);
  await page.getByRole('button', { name: 'Autorizar equipo' }).click();
  await expect(page.getByText('Equipo autorizado', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Cerrar', exact: true }).click();
  await page.getByRole('button', { name: 'Desactivar Tableta de visitas' }).click();
  await page.getByRole('button', { name: 'Desactivar equipo', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Desactivar Tableta de visitas' })).toHaveCount(0);
  await page.getByRole('button', { name: 'Estado del sistema', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Sincronización de pases' })).toBeVisible();
  await page.getByRole('navigation', { name: 'Navegación principal' }).getByRole('button', { name: 'Inicio', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('navigation', { name: 'Navegación móvil' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/dashboard-mobile.png', fullPage: true });
  await page.getByRole('navigation', { name: 'Navegación móvil' }).getByRole('button', { name: 'Dispositivos' }).click();
  await expect(page.getByRole('heading', { name: 'Mis dispositivos' })).toBeVisible();
  await page.getByRole('button', { name: 'Abrir menú' }).click();
  await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Qué gusto verte.' })).toBeVisible();
  await page.getByRole('button', { name: 'Ingresar con mi llave' }).click();
  await expect(page.getByRole('heading', { name: 'Hola, Lucía.' })).toBeVisible();
  const residentContext = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const residentPage = await residentContext.newPage();
  const residentCdp = await residentContext.newCDPSession(residentPage); await residentCdp.send('WebAuthn.enable');
  await residentCdp.send('WebAuthn.addVirtualAuthenticator', { options: { protocol: 'ctap2', transport: 'internal', hasResidentKey: true, hasUserVerification: true, isUserVerified: true, automaticPresenceSimulation: true } });
  await residentPage.goto(residentInvite);
  await residentPage.getByRole('button', { name: 'Activar mi acceso', exact: true }).click();
  await expect(residentPage.getByRole('heading', { name: 'Hola, Ana.' })).toBeVisible();
  await expect(residentPage.getByRole('button', { name: 'Administración', exact: true })).toHaveCount(0);
  await expect(residentPage.getByRole('button', { name: 'Caseta', exact: true })).toHaveCount(0);
  await expect(residentPage.getByRole('button', { name: /Valeria Pérez/ })).toHaveCount(0);
  await residentPage.getByRole('navigation', { name: 'Navegación móvil' }).getByRole('button', { name: 'Dispositivos' }).click();
  await expect(residentPage.getByRole('heading', { name: 'Mi dispositivo', exact: true })).toBeVisible();
  await residentPage.getByRole('button', { name: 'Eliminar Mi dispositivo', exact: true }).click();
  await residentPage.getByRole('button', { name: 'Eliminar llave', exact: true }).click();
  await expect(residentPage.getByRole('heading', { name: 'Qué gusto verte.' })).toBeVisible();
  await residentContext.close();
  // API and bearer QR paths are never stored in Cache Storage.
  await page.evaluate(async () => { await navigator.serviceWorker.ready; });
  await page.goto(shared);
  await expect(page.getByRole('img', { name: 'Código QR de acceso' })).toBeVisible();
  await page.screenshot({ path: 'test-results/visitor-mobile.png', fullPage: true });
  const cached = await page.evaluate(async () => { const urls: string[] = []; for (const key of await caches.keys()) for (const req of await (await caches.open(key)).keys()) urls.push(req.url); return urls; });
  expect(cached.length).toBeGreaterThan(0); expect(cached.some(url => /\/api\/|\/p\//.test(url))).toBe(false);
  await context.setOffline(true); await page.reload();
  await expect(page.getByRole('img', { name: 'Código QR de acceso' })).toBeVisible();
  await expect(page.getByText(/Puedes mostrar este QR sin conexión/)).toBeVisible();
  await context.setOffline(false);
  expect(errors).toEqual([]);
});
