import { useState, type FormEvent } from 'react';
import { DoorOpen, Pencil, Plus, Tablet } from 'lucide-react';
import { useMutation, useQuery, dateText } from '../hooks';
import type { Gate, GateDevice, Page } from '../types';
import { Button, Empty, ErrorBox, Info, Loading, Modal } from '../components/ui';
import TrashIcon from '../components/icons/AnimatedTrash';
import { Secret } from './AdminSecret';

export function AdminGateDevices() {
  const [cursor, setCursor] = useState(''); const devices = useQuery<Page<GateDevice>>('/admin/gate-devices' + (cursor ? '?cursor=' + cursor : '')); const gates = useQuery<Page<Gate>>('/gate/gates'); const [create, setCreate] = useState(false); const [gateId, setGateId] = useState(''); const [label, setLabel] = useState(''); const [secret, setSecret] = useState<{ deviceToken: string } | null>(null); const [remove, setRemove] = useState<GateDevice | null>(null); const mutation = useMutation();
  async function submit(e: FormEvent) { e.preventDefault(); const value = await mutation.run<{ deviceToken: string }>('/admin/gate-devices', 'POST', { gateId, label }); if (value) { setSecret(value); devices.refresh(); } }
  async function revoke() { const value = await mutation.run(`/admin/gate-devices/${remove!.id}`, 'DELETE'); if (value) { setRemove(null); devices.refresh(); } }
  const activeDevices = (id: string) => devices.data?.data.filter(d => d.gateId === id && d.active).length ?? 0;
  return <div className="stack gates-admin">
    <GatesPanel gates={gates} activeDevices={activeDevices} onChanged={() => { gates.refresh(); devices.refresh(); }} onAddDevice={id => { setGateId(id); setCreate(true); setSecret(null); setLabel(''); mutation.clear(); }}/>
    <section className="panel"><div className="panel-heading"><div><h2>Equipos autorizados</h2><p>Genera una clave de vinculación para cada equipo. Se usa una sola vez.</p></div><Button disabled={!gates.data?.data.length} onClick={() => { setCreate(true); setSecret(null); setLabel(''); setGateId(gates.data?.data.length === 1 ? gates.data.data[0].id : ''); mutation.clear(); }}><Plus size={17}/> Agregar equipo</Button></div><ErrorBox message={devices.error} retry={devices.refresh}/>{devices.loading ? <Loading/> : !devices.data?.data.length ? <Empty icon={<Tablet/>} title="Aún no hay equipos" text={gates.data?.data.length ? 'Registra el primer dispositivo que se usará en una caseta.' : 'Primero crea una caseta.'}/> : <div className="device-list">{devices.data.data.map(d => <div className="device-row" key={d.id}><span className="device-symbol"><Tablet/></span><div><h3>{d.label}</h3><p>{d.gate.label} · {d.active ? 'Autorizado' : 'Desactivado'}</p><small>{d.pairedAt ? 'Vinculado el ' + dateText(d.pairedAt) : 'Pendiente de vincular'} · Registrado el {dateText(d.createdAt)}</small></div>{d.active && <button className="icon-button danger-text" aria-label={`Desactivar ${d.label}`} onClick={() => { setRemove(d); mutation.clear(); }}><TrashIcon size={18}/></button>}</div>)}</div>}<div className="pager">{cursor && <Button className="secondary" onClick={() => setCursor('')}>Volver al inicio</Button>}{devices.data?.nextCursor && <Button className="secondary" onClick={() => setCursor(devices.data!.nextCursor!)}>Más equipos</Button>}</div>{create && <Modal title="Agregar equipo de caseta" onClose={() => { if (!mutation.busy) setCreate(false); }}>{secret ? <Secret title="Clave de vinculación de un solo uso" value={secret.deviceToken}/> : <form onSubmit={submit}><fieldset disabled={mutation.busy}><label>Nombre del equipo<input required maxLength={100} value={label} onChange={e => setLabel(e.target.value)} placeholder="Por ejemplo: Tableta de entrada"/></label><label>Caseta<select required value={gateId} onChange={e => setGateId(e.target.value)}><option value="">Selecciona una caseta</option>{gates.data?.data.map(g => <option value={g.id} key={g.id}>{g.label}</option>)}</select></label></fieldset><ErrorBox message={gates.error} retry={gates.refresh}/><ErrorBox message={mutation.error}/><div className="modal-actions"><Button type="submit" busy={mutation.busy}>Autorizar equipo</Button></div></form>}</Modal>}{remove && <Modal title="¿Desactivar este equipo?" onClose={() => { if (!mutation.busy) setRemove(null); }}><p><strong>{remove.label}</strong> dejará de validar pases de inmediato. Para volver a usarlo habrá que registrar y vincular otro equipo.</p><ErrorBox message={mutation.error}/><div className="modal-actions"><Button className="secondary" disabled={mutation.busy} onClick={() => setRemove(null)}>Conservar</Button><Button className="danger" busy={mutation.busy} onClick={revoke}><TrashIcon size={17}/> Desactivar equipo</Button></div></Modal>}</section>
  </div>;
}

// The fraccionamiento's casetas: as many as it needs, each letting in visitors of any home.
function GatesPanel({ gates, activeDevices, onChanged, onAddDevice }: { gates: ReturnType<typeof useQuery<Page<Gate>>>; activeDevices: (id: string) => number; onChanged: () => void; onAddDevice: (id: string) => void }) {
  const [editing, setEditing] = useState<Gate | 'new' | null>(null); const [name, setName] = useState(''); const [archive, setArchive] = useState<Gate | null>(null);
  const mutation = useMutation();
  function open(target: Gate | 'new') { setEditing(target); setName(target === 'new' ? '' : target.label); mutation.clear(); }
  async function save(e: FormEvent) {
    e.preventDefault();
    const ok = editing === 'new' ? await mutation.run('/admin/gates', 'POST', { label: name.trim() }) : await mutation.run(`/admin/gates/${(editing as Gate).id}`, 'PATCH', { label: name.trim() });
    if (ok) { setEditing(null); onChanged(); }
  }
  async function confirmArchive() { if (await mutation.run(`/admin/gates/${archive!.id}`, 'DELETE')) { setArchive(null); onChanged(); } }
  const list = gates.data?.data ?? [];
  return <section className="panel">
    <div className="panel-heading"><div><h2>Casetas</h2><p>Cada caseta deja entrar a las visitas de cualquier casa del fraccionamiento. Crea las que necesites.</p></div><Button onClick={() => open('new')}><Plus size={17}/> Nueva caseta</Button></div>
    <ErrorBox message={gates.error} retry={gates.refresh}/>
    {gates.loading && !gates.data ? <Loading/> : !list.length ? <Empty icon={<DoorOpen/>} title="Aún no hay casetas" text="Crea la primera, por ejemplo «Acceso principal», y después vincula su equipo."/> :
      <div className="device-list">{list.map(g => <div className="device-row" key={g.id}><span className="device-symbol"><DoorOpen/></span><div><h3>{g.label}</h3><p>{activeDevices(g.id) === 1 ? '1 equipo autorizado' : `${activeDevices(g.id)} equipos autorizados`}</p></div>
        <div className="gate-actions"><Button className="secondary small-button" onClick={() => onAddDevice(g.id)}><Tablet size={15}/> Agregar equipo</Button><button className="icon-button" aria-label={`Cambiar nombre de ${g.label}`} onClick={() => open(g)}><Pencil size={17}/></button><button className="icon-button danger-text" aria-label={`Eliminar ${g.label}`} onClick={() => { setArchive(g); mutation.clear(); }}><TrashIcon size={18}/></button></div></div>)}</div>}
    {editing && <Modal title={editing === 'new' ? 'Nueva caseta' : 'Cambiar nombre'} onClose={() => { if (!mutation.busy) setEditing(null); }}><form onSubmit={save}><fieldset disabled={mutation.busy}><label>Nombre de la caseta<input autoFocus required minLength={2} maxLength={80} value={name} onChange={e => setName(e.target.value)} placeholder="Por ejemplo: Acceso principal"/></label></fieldset><ErrorBox message={mutation.error}/><div className="modal-actions"><Button className="secondary" disabled={mutation.busy} onClick={() => setEditing(null)}>Cancelar</Button><Button type="submit" busy={mutation.busy}>{editing === 'new' ? 'Crear caseta' : 'Guardar'}</Button></div></form></Modal>}
    {archive && <Modal title="¿Eliminar esta caseta?" onClose={() => { if (!mutation.busy) setArchive(null); }}><p><strong>{archive.label}</strong> dejará de existir y sus equipos dejarán de validar pases de inmediato.</p><Info>El historial de sus lecturas se conserva en Movimientos.</Info><ErrorBox message={mutation.error}/><div className="modal-actions"><Button className="secondary" disabled={mutation.busy} onClick={() => setArchive(null)}>Conservar</Button><Button className="danger" busy={mutation.busy} onClick={confirmArchive}><TrashIcon size={17}/> Eliminar caseta</Button></div></Modal>}
  </section>;
}
