import { useState } from 'react';
import { Activity, RefreshCw, ShieldCheck } from 'lucide-react';
import { useMutation, useQuery, dateText } from '../hooks';
import type { Health, Outbox, Page } from '../types';
import { Button, Empty, ErrorBox, Loading, Success } from '../components/ui';

export function AdminSystemStatus() {
  const health = useQuery<Health>('/admin/sync-health', 15000); const [state, setState] = useState('FAILED'); const [cursor, setCursor] = useState(''); const events = useQuery<Page<Outbox>>(`/admin/outbox?status=${state}${cursor ? '&cursor=' + cursor : ''}`, 15000); const mutation = useMutation(); const [done, setDone] = useState(false);
  async function retry(id: string) { setDone(false); const result = await mutation.run(`/admin/outbox/${id}/retry`, 'POST', {}); if (result) { setDone(true); events.refresh(); health.refresh(); } }
  return <><div className="stat-grid three">{[['Cambios pendientes', health.data?.pending], ['Requieren atención', health.data?.failed], ['Sincronización promedio', health.data ? `${Math.round(health.data.averagePropagationMs)} ms` : undefined]].map(([name, n]) => <div className="stat-card" key={name}><span className="stat-icon green"><Activity size={20}/></span><span><small>{name}</small><strong>{n ?? '—'}</strong></span></div>)}</div><ErrorBox message={health.error} retry={health.refresh}/><section className="panel"><div className="panel-heading"><div><h2>Sincronización de pases</h2><p>Los permisos se guardan antes de sincronizar los cambios.</p></div><Button className="secondary small-button" onClick={() => { health.refresh(); events.refresh(); }}><RefreshCw size={16}/> Actualizar</Button></div><div className="tabs padded"><button className={state === 'FAILED' ? 'active' : ''} onClick={() => { setState('FAILED'); setCursor(''); }}>Requieren atención</button><button className={state === 'PENDING' ? 'active' : ''} onClick={() => { setState('PENDING'); setCursor(''); }}>Pendientes</button></div><ErrorBox message={events.error} retry={events.refresh}/><ErrorBox message={mutation.error}/>{done && <Success>Se solicitó el reintento de sincronización.</Success>}{events.loading && !events.data ? <Loading/> : !events.data?.data.length ? <Empty icon={<ShieldCheck/>} title="Todo al día" text="No hay cambios en este estado."/> : <div className="event-list">{events.data.data.map(e => <div key={e.id}><span className="stat-icon sand"><RefreshCw size={18}/></span><span><strong>{({ PASS_CREATED: 'Pase creado', PASS_REVOKED: 'Pase cancelado', PASS_USED: 'Pase utilizado', PASS_EXPIRED: 'Pase vencido' } as Record<string, string>)[e.eventType] ?? 'Cambio de pase'}</strong><small>{dateText(e.createdAt)} · {e.retries} reintentos</small></span>{e.status === 'FAILED' && <Button className="secondary small-button" busy={mutation.busy} onClick={() => retry(e.id)}>Reintentar</Button>}</div>)}</div>}<div className="pager">{cursor && <Button className="secondary" onClick={() => setCursor('')}>Volver al inicio</Button>}{events.data?.nextCursor && <Button className="secondary" onClick={() => setCursor(events.data!.nextCursor!)}>Más cambios</Button>}</div></section></>;
}
