import { useState, type FormEvent } from 'react';
import { Plus, Tablet } from 'lucide-react';
import { useMutation, useQuery, dateText } from '../hooks';
import type { Gate, GateDevice, Page } from '../types';
import { Button, Empty, ErrorBox, Loading, Modal } from '../components/ui';
import TrashIcon from '../components/icons/AnimatedTrash';
import { Secret } from './AdminSecret';

export function AdminGateDevices() {
  const [cursor, setCursor] = useState(''); const devices = useQuery<Page<GateDevice>>('/admin/gate-devices' + (cursor ? '?cursor=' + cursor : '')); const gates = useQuery<Page<Gate>>('/gate/gates'); const [create, setCreate] = useState(false); const [gateId, setGateId] = useState(''); const [label, setLabel] = useState(''); const [secret, setSecret] = useState<{ deviceToken: string } | null>(null); const [remove, setRemove] = useState<GateDevice | null>(null); const mutation = useMutation();
  async function submit(e: FormEvent) { e.preventDefault(); const value = await mutation.run<{ deviceToken: string }>('/admin/gate-devices', 'POST', { gateId, label }); if (value) { setSecret(value); devices.refresh(); } }
  async function revoke() { const value = await mutation.run(`/admin/gate-devices/${remove!.id}`, 'DELETE'); if (value) { setRemove(null); devices.refresh(); } }
  return <section className="panel"><div className="panel-heading"><div><h2>Equipos autorizados</h2><p>Genera una clave de vinculación para cada equipo. Se usa una sola vez.</p></div><Button onClick={() => { setCreate(true); setSecret(null); setLabel(''); setGateId(''); mutation.clear(); }}><Plus size={17}/> Agregar equipo</Button></div><ErrorBox message={devices.error} retry={devices.refresh}/>{devices.loading ? <Loading/> : !devices.data?.data.length ? <Empty icon={<Tablet/>} title="Aún no hay equipos" text="Registra el primer dispositivo que se usará en una caseta."/> : <div className="device-list">{devices.data.data.map(d => <div className="device-row" key={d.id}><span className="device-symbol"><Tablet/></span><div><h3>{d.label}</h3><p>{d.gate.label} · {d.active ? 'Autorizado' : 'Desactivado'}</p><small>{d.pairedAt ? 'Vinculado el ' + dateText(d.pairedAt) : 'Pendiente de vincular'} · Registrado el {dateText(d.createdAt)}</small></div>{d.active && <button className="icon-button danger-text" aria-label={`Desactivar ${d.label}`} onClick={() => { setRemove(d); mutation.clear(); }}><TrashIcon size={18}/></button>}</div>)}</div>}<div className="pager">{cursor && <Button className="secondary" onClick={() => setCursor('')}>Volver al inicio</Button>}{devices.data?.nextCursor && <Button className="secondary" onClick={() => setCursor(devices.data!.nextCursor!)}>Más equipos</Button>}</div>{create && <Modal title="Agregar dispositivo de caseta" onClose={() => { if (!mutation.busy) setCreate(false); }}>{secret ? <Secret title="Clave de vinculación de un solo uso" value={secret.deviceToken}/> : <form onSubmit={submit}><fieldset disabled={mutation.busy}><label>Nombre del equipo<input required maxLength={100} value={label} onChange={e => setLabel(e.target.value)} placeholder="Por ejemplo: Tableta de entrada"/></label><label>Caseta<select required value={gateId} onChange={e => setGateId(e.target.value)}><option value="">Selecciona una caseta</option>{gates.data?.data.map(g => <option value={g.id} key={g.id}>{g.label}</option>)}</select></label></fieldset><ErrorBox message={gates.error} retry={gates.refresh}/><ErrorBox message={mutation.error}/><div className="modal-actions"><Button type="submit" busy={mutation.busy}>Autorizar equipo</Button></div></form>}</Modal>}{remove && <Modal title="¿Desactivar este equipo?" onClose={() => { if (!mutation.busy) setRemove(null); }}><p><strong>{remove.label}</strong> dejará de validar pases de inmediato. Para volver a usarlo habrá que registrar y vincular otro equipo.</p><ErrorBox message={mutation.error}/><div className="modal-actions"><Button className="secondary" disabled={mutation.busy} onClick={() => setRemove(null)}>Conservar</Button><Button className="danger" busy={mutation.busy} onClick={revoke}><TrashIcon size={17}/> Desactivar equipo</Button></div></Modal>}</section>;
}
